# Site settings
title: MBassador meets Microservices
email: m.gonzalez@student.fontys.nl
description: > # this means to ignore newlines until "baseurl:"
  This website is teaching to you the advantage of using an event bus such as
  MBassador together with microservices.
baseurl: "/microservices-eventbus/" # the subpath of your site, e.g. /blog/
url: "http://sebivenlo.github.io/" # the base hostname & protocol for your site
twitter_username: tweetmyreality
github_username:  MyRealityCoding

# Build settings
markdown: kramdown
